module "aks_main" {
  source                            = "./modules/aks"
  cluster_name                      = var.aks_main_cluster_name
  registry_name                     = var.aks_main_registry_name
  registry_resource_group_name      = var.aks_main_registry_resource_group_name
  dns_prefix                        = var.aks_main_dns_prefix
  local_account_disabled            = var.aks_main_local_account_disabled
  private_cluster_enabled           = var.aks_main_private_cluster_enabled
  resource_group_location           = module.resource_group_spoke_1.location
  resource_group_name               = module.resource_group_spoke_1.name
  default_node_name                 = var.aks_main_default_node_name
  default_node_vm_size              = var.aks_main_default_node_vm_size
  default_node_subnet_id            = module.subnet_spoke_1_aks.id
  default_node_zones                = var.aks_main_default_node_zones
  default_node_type                 = var.aks_main_default_node_type
  enable_auto_scaling               = var.aks_main_enable_auto_scaling
  default_node_min_count            = var.aks_main_default_node_min_count
  default_node_max_count            = var.aks_main_default_node_max_count
  default_node_max_pods             = var.aks_main_default_node_max_pods
  default_node_os_disk_size_gb      = var.aks_main_default_node_os_disk_size_gb
  network_profile_plugin            = var.aks_main_network_profile_plugin
  network_profile_policy            = var.aks_main_network_profile_policy
  network_profile_load_balancer_sku = var.aks_main_network_profile_load_balancer_sku
  identity_type                     = var.aks_main_identity_type
  azure_policy_enabled              = var.aks_main_azure_policy_enabled
  tags                              = var.aks_main_tags
}
