apiVersion: networking.gke.io/v1
kind: GCPGatewayPolicy
metadata:
  name: sap-clifre-gw-global-access-policy
  namespace: {NAMESPACE}
spec:
  default:
    allowGlobalAccess: true
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: sap-clifre-internal-gateway